name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: build

      - name: Build Theme
        env:
          working_directory: "build/themes/workflow-wpe"
          script: "entrypoint.sh"