name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: "entrypoint.sh"
        shell: bash
        env:
          working_directory: "build/themes/workflow-wpe"