name: Deploy to WP Engine
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
      # Deploy vars 
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: mindgrub
        # Deploy Options
        REMOTE_PATH: "wp-content/themes/workflow-wpe/"
        PHP_LINT: TRUE
        SCRIPT: "./entrypoint"
        CACHE_CLEAR: TRUE