name: Deploy to WPEngine - MAIN
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Dependencies
        run: |
          cd ./
          echo "Installing NVM"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          echo "Load Bash Completion"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          echo "Install and Use NVM 14"
          nvm install 14
          nvm use 14
          echo "Initiating NPM Install"
          npm install
          echo "Building Theme"
          npm run build
          echo "Removing Node Modules"
          rm -rf node_modules/
      - name: Deploy to WPEngine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
          #Deploy Variables
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: mindgrub
          REMOTE_PATH: "wp-content/themes/workflow-wpe/"
          CACHE_CLEAR: TRUE