name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
          uses: actions/checkout@v3
      - name: Build Dependencies
        run: ./entrypoint.sh
        with:
        # Deploy vars 
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: mindgrub
          REMOTE_PATH: "wp-content/themes/workflow-wpe/"
          CACHE_CLEAR: TRUE
      - name: deploy to wpengine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
        # Deploy vars 
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: mindgrub
          REMOTE_PATH: "wp-content/themes/workflow-wpe/"
          CACHE_CLEAR: TRUE
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Navigate To Root
  #       run: cd ~/
  #     - name: Permissions
  #       run: chmod +x entrypoint.sh
  #     - name: dependencies
        # with:
        # # Deploy vars 
        #   WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        #   WPE_ENV: mindgrub
        #   REMOTE_PATH: "wp-content/themes/workflow-wpe/"
        #   CACHE_CLEAR: TRUE
        # run: ssh $WPE_SITE_NAME@$WPE_SSH_HOST -i $SSH_PRIVATE_ACCOUNT_KEY_PATH -o UserKnownHostsFile=$KNOWN_HOSTS_PATH << EOF