name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Dependencies
        run: |
          cd ./
          echo "NVM"
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install 14
          nvm use 14
          echo "Initiating NPM Install"
          npm install
          echo "Building"
          npm run build
      - name: deploy to wpengine
        run: ./deploy.sh
        inputs:
          WPE_SSHG_KEY_PRIVATE:
            description: "The private RSA key you will save in the Github Secrets"
            required: true
          PHP_LINT:
            description: "optional php syntax check"
            required: false
            default: false
          FLAGS: 
            description: "Optional flags for the deployment"
            required: true
            default: '-azvr --inplace --exclude=".*"'
          CACHE_CLEAR:
            description: "Optional WPE Clear cache"
            required: false
            default: true
          SRC_PATH:
            description: "An optional source directory to deploy other than the root directory that is being versioned."
            default: "."
            required: false
          REMOTE_PATH:
            description: "An optional destination directory to deploy to other than the WordPress root."
            default: ""
            required: false
          WPE_ENV:
            description: "Destination to deploy to WPE"
            required: false
          PRD_ENV:
            description: "Destination to deploy to WPE Prod"
            required: false
          STG_ENV:
            description: "Destination to deploy to WPE Stage"
            required: false
          DEV_ENV:
            description: "Destination to deploy to WPE Dev"
            required: false
          SCRIPT: 
            description: "File containing custom scripts run after the rsync"
            required: false
        with:
        # Deploy vars 
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: mindgrub
          REMOTE_PATH: "wp-content/themes/workflow-wpe/"
          CACHE_CLEAR: TRUE
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Navigate To Root
  #       run: cd ~/
  #     - name: Permissions
  #       run: chmod +x entrypoint.sh
  #     - name: dependencies
        # with:
        # # Deploy vars 
        #   WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        #   WPE_ENV: mindgrub
        #   REMOTE_PATH: "wp-content/themes/workflow-wpe/"
        #   CACHE_CLEAR: TRUE
        # run: ssh $WPE_SITE_NAME@$WPE_SSH_HOST -i $SSH_PRIVATE_ACCOUNT_KEY_PATH -o UserKnownHostsFile=$KNOWN_HOSTS_PATH << EOF