name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Navigate To Root
        run: cd ../
      - name: Look
        run: ls
      - name: Install
        run: npm install