name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        working-directory: ./
        run: npm install