name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Permissions
        run: |
          chmod +x entrypoint.sh
          chmod +x deploy.sh
      - name: Build Dependencies
        run: |
          ./deploy.sh
        env:
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: mindgrub
          REMOTE_PATH: "wp-content/themes/workflow-wpe/"
          CACHE_CLEAR: TRUE