name: Deploy to WPEngine
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Navigate To Root
        run: cd home/runner/work/workflow-wpe
      - name: Install
        run: npm install