name: Deploy to WPEngine
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: build

      - name: Build Theme
        uses: linchpin/action-build-yarn-npm@master
        env:
          working_directory: "build/themes/workflow-wpe"