name: Deploy to WPEngine - STG
on:
  push:
    branches:
      - 'stage'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # Load theme specific ENV variables
      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
      - name: Build Dependencies
        run:
          #Update Build Script Permissions and run Build Script 
          |
          chmod +x .github/build.sh
          .github/build.sh
      - name: Deploy to WPEngine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
          #WPEngine Deploy Variables
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: ${{ env.STG_ENVIRONMENT }}
          REMOTE_PATH: "wp-content/themes/${{ env.THEME_NAME }}/"
          CACHE_CLEAR: TRUE