name: Deploy to WPEngine - STG
on:
  push:
    branches:
      - 'stage'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Dependencies
        run: |
          chmod +x .github/build.sh
          .github/build.sh
      - name: Deploy to WPEngine
        uses: wpengine/github-action-wpe-site-deploy@v3.0
        with:
          #Deploy Variables
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
          WPE_ENV: stgmindgrub
          REMOTE_PATH: "wp-content/themes/workflow-wpe/"
          CACHE_CLEAR: TRUE